packages:
  autoconf:
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    externals:
    - spec: automake@1.15.1
      prefix: /usr
  bash:
    externals:
    - spec: bash@4.4.23
      prefix: /
  bison:
    externals:
    - spec: bison@3.0.4
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
  cmake:
    externals:
    - spec: cmake@3.21.3
      prefix: /sw/spock/spack-envs/base/opt/cray-sles15-zen2/cce-12.0.3/cmake-3.21.3-mcm2asg4suzqa4yoyjznyir65lmdlwcy
    - spec: cmake@3.17.0
      prefix: /usr
  cpio:
    externals:
    - spec: cpio@2.12
      prefix: /usr
  diffutils:
    externals:
    - spec: diffutils@3.6
      prefix: /usr
  file:
    externals:
    - spec: file@5.32
      prefix: /usr
  findutils:
    externals:
    - spec: findutils@4.6.0
      prefix: /
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gawk:
    externals:
    - spec: gawk@4.2.1
      prefix: /usr
  ghostscript:
    externals:
    - spec: ghostscript@9.52
      prefix: /usr
  git:
    externals:
    - spec: git@2.26.2~tcltk
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.2.1
      prefix: /usr
  groff:
    externals:
    - spec: groff@1.22.3
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.6
      prefix: /usr
  m4:
    externals:
    - spec: m4@1.4.18
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@6.1.20180317+termlib abi=6
      prefix: /usr
  openssh:
    externals:
    - spec: openssh@8.1p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@1.1.1d
      prefix: /usr
  perl:
    externals:
    - spec: perl@5.26.1~cpanm+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@3.1.3
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.5.9
      prefix: /usr
  sed:
    externals:
    - spec: sed@4.4
      prefix: /usr
  tar:
    externals:
    - spec: tar@1.30
      prefix: /usr
  texinfo:
    externals:
    - spec: texinfo@6.5
      prefix: /usr
  xz:
    externals:
    - spec: xz@5.2.3
      prefix: /usr
  cray-mpich:
    buildable: false
    compiler: []
    externals:
      - modules:
          - cray-mpich/8.1.7
        spec: cray-mpich@8.1.7
      - modules:
          - cray-mpich/8.1.6
        spec: cray-mpich@8.1.6
      - modules:
          - cray-mpich/8.1.4
        spec: cray-mpich@8.1.4
    providers: {}
    target: []
    version: [8.1.7, 8.1.6, 8.1.4]
  llvm-amdgpu:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0/llvm
        spec: llvm-amdgpu@4.3.0
      - prefix: /opt/rocm-4.2.0/llvm
        spec: llvm-amdgpu@4.2.0
      - prefix: /opt/rocm-4.1.0/llvm
        spec: llvm-amdgpu@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  cray-libsci:
    buildable: false
    externals:
      - modules:
          - cray-libsci/21.06.1.1
          - cray-mpich/8.1.7
        spec: cray-libsci@21.06.1.1
      - modules:
          - cray-libsci/21.04.1.1
        spec: cray-libsci@21.04.1.1
    version: [21.06.1.1]
  hip:
    buildable: false
    externals:
      - extra_attributes:
          compilers:
            hip: /opt/rocm-4.3.0/hip/bin/hipcc
        prefix: /opt/rocm-4.3.0/hip
        spec: hip@4.3.0
      - extra_attributes:
          compilers:
            hip: /opt/rocm-4.2.0/hip/bin/hipcc
        prefix: /opt/rocm-4.2.0/hip
        spec: hip@4.2.0
      - extra_attributes:
          compilers:
            hip: /opt/rocm-4.1.0/hip/bin/hipcc
        prefix: /opt/rocm-4.1.0/hip
        spec: hip@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hip-rocclr:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0/rocclr
        spec: hip-rocclr@4.3.0
      - prefix: /opt/rocm-4.2.0/rocclr
        spec: hip-rocclr@4.2.0
      - prefix: /opt/rocm-4.1.0/rocclr
        spec: hip-rocclr@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hipblas:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hipblas@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hipblas@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hipblas@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hipcub:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hipcub@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hipcub@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hipcub@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hipfft:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hipfft@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hipfft@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hipfft@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hipfort:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hipfort@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hipfort@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hipfort@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hipify-clang:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0 #FIXME
        spec: hipify-clang@4.3.0
      - prefix: /opt/rocm-4.2.0 #FIXME
        spec: hipify-clang@4.2.0
      - prefix: /opt/rocm-4.1.0 #FIXME
        spec: hipify-clang@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hipsparse:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hipsparse@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hipsparse@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hipsparse@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hsa-rocr-dev:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hsa-rocr-dev@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hsa-rocr-dev@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hsa-rocr-dev@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  hsakmt-roct:
    buildable: false
    externals:
      - prefix: /opt/rocm-4.3.0
        spec: hsakmt-roct@4.3.0
      - prefix: /opt/rocm-4.2.0
        spec: hsakmt-roct@4.2.0
      - prefix: /opt/rocm-4.1.0
        spec: hsakmt-roct@4.1.0
    version: [4.3.0, 4.2.0, 4.1.0]
  all:
    compiler: [gcc, intel, pgi, clang, xl, nag, fj, aocc]
    providers:
      awk: [gawk]
      blas: [openblas, amdblis]
      D: [ldc]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw, amdfftw]
      flame: [libflame, amdlibflame]
      fuse: [libfuse]
      gl: [mesa+opengl, mesa18, opengl]
      glu: [mesa-glu, openglu]
      glx: [mesa+glx, mesa18+glx, opengl]
      golang: [gcc]
      iconv: [libiconv]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      blas: [cray-libsci@21.06.1.1]
      lapack: [cray-libsci@21.06.1.1]
      lua-lang: [lua, lua-luajit]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mpich]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      onedal: [intel-oneapi-dal]
      osmesa: [mesa+osmesa, mesa18+osmesa]
      pbs: [openpbs, torque]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      rpc: [libtirpc]
      scalapack: [netlib-scalapack, amdscalapack]
      sycl: [hipsycl]
      szip: [libaec, libszip]
      tbb: [intel-tbb]
      unwind: [libunwind]
      uuid: [util-linux-uuid, libuuid]
      xxd: [xxd-standalone, vim]
      yacc: [bison, byacc]
      ziglang: [zig]
    permissions:
      read: world
      write: user



