packages:
  all:
    variants: +openmp+python
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [spectrum-mpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
      uuid: [util-linux-uuid, libuuid]
# choices
  hdf5:
    variants: ~mpi
  python:
    variants: ~dbm~libxml2
  py-numpy:
    variants: ~blas~lapack
# system libs
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl@5.26.3
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config@1.4.2
  cuda:
    buildable: false
    externals:
    - prefix: /sw/summit/cuda/11.0.3/
      spec: cuda@11.0.3
  spectrum-mpi:
    buildable: false
    externals:
    - prefix: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-2s7kpbzydf6val7k2d3e6cz3zdhtcwlw/
      spec: spectrum-mpi@10.4.0%gcc
  cmake:
    buildable: false
    externals:
    - prefix: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-8.3.1/cmake-3.21.3-ryec5weswyjqidpbl2b5ye6gvq4uumod/
      spec: cmake@3.21.3%gcc
      modules:
         - cmake/3.21.3

