packages:
  all:
    variants: cuda_arch=70
    compiler: [gcc]
    providers:
      mpi: [mpich]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
      uuid: [util-linux-uuid, libuuid]
  cuda:
    buildable: false
    externals:
    - prefix: /usr/local/cuda/
      spec: cuda@11.4
  netlib-lapack:
    buildable: false
    externals:
    - prefix: /usr/
      spec: netlib-lapack
  mpich:
    buildable: false
    externals:
    - prefix: /usr
      spec: mpich
  bzip2:
    buildable: false
    externals:
    - prefix: /usr
      spec: bzip2
  readline:
    buildable: false
    externals:
    - prefix: /usr
      spec: readline
  sqlite:
    buildable: false
    externals:
    - prefix: /usr
      spec: sqlite
  ncurses:
    buildable: false
    externals:
    - prefix: /usr
      spec: ncurses
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
  openssl:
    buildable: false
    externals:
    - prefix: /usr
      spec: openssl
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  tar:
    buildable: false
    externals:
    - prefix: /usr
      spec: tar
