packages:
  all:
    compiler: [clang, gcc, intel, pgi, xl, nag, fj]
    variants: ~openmp
    providers:
      D: [ldc]
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      fftw-api: [fftw]
      gl: [mesa+opengl, opengl]
      glx: [mesa+glx, opengl]
      glu: [mesa-glu, openglu]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [openjdk, jdk, ibm-java]
      jpeg: [libjpeg-turbo, libjpeg]
      lapack: [openblas]
      mariadb-client: [mariadb-c-client, mariadb]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [mpich, openmpi]
      mysql-client: [mysql, mariadb-c-client]
      opencl: [pocl]
      pil: [py-pillow]
      pkgconfig: [pkgconf, pkg-config]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      unwind: [libunwind]
    permissions:
      read: world
      write: user
# custom variants
  conduit:
    version: [master]
  python:
    variants: +shared~dbm
  # python 2 constraints
  py-sphinx:
    version: [1.8.4]
  py-numpy:
    version: [1.16.5]
  cmake:
    variants: ~openssl~ncurses
  hwloc:
    variants: ~libxml2
  perl:
    buildable: false
    externals:
    - prefix: /usr/
      spec: perl
