compilers::
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /opt/rocm/llvm/bin/amdclang
      cxx: /opt/rocm/llvm/bin/amdclang++
      f77: /opt/rocm/llvm/bin/amdflang
      fc: /opt/rocm/llvm/bin/amdflang
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64 
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@9.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
