compilers::
- compiler:
    spec: clang@14.0.0
    paths:
      cc: /opt/rocm/llvm/bin/amdclang
      cxx: /opt/rocm/llvm/bin/amdclang++
      f77: /opt/rocm/llvm/bin/amdflang
      fc: /opt/rocm/llvm/bin/amdflang
    flags: {}
    target: x86_64 
    modules: []
    environment: {}
    extra_rpaths: []
