packages:
  all:
    variants: cuda_arch=80 +cuda~openmp~python~shared~mfem
    compiler: [gcc@11.2.0]
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
      uuid: [util-linux-uuid, libuuid]
  mpich:
    version: [8.1.12]
    buildable: false
    providers: {}
    compiler: []
    externals:
    - modules:
      - cray-mpich/8.1.12
      spec: mpich@8.1.12
  openssl:
    buildable: false
    externals:
    - prefix: /usr
      spec: openssl
  cuda:
    buildable: false
    externals:
    - prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.0/
      spec: cuda@11.0.0
      modules:
        - cudatoolkit/21.9_11.0
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
