compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    - PrgEnv-gnu/8.3.3 
    - cudatoolkit/11.5
    operating_system: sles15
    paths:
      cc: /opt/cray/pe/craype/2.7.15/bin/cc #gcc
      cxx: /opt/cray/pe/craype/2.7.15/bin/CC #g++
      f77: /opt/cray/pe/craype/2.7.15/bin/ftn # gfortran
      fc: /opt/cray/pe/craype/2.7.15/bin/ftn #gfortran
    spec: gcc@11.2.0
    target: any
