packages:
  all:
    variants: cuda_arch=70 +cuda~openmp~python~shared~mfem
    compiler: [gcc, intel, pgi, clang, xl, nag]
    providers:
      awk: [gawk]
      blas: [openblas]
      daal: [intel-daal]
      elf: [elfutils]
      golang: [gcc]
      ipp: [intel-ipp]
      java: [jdk]
      lapack: [openblas]
      mkl: [intel-mkl]
      mpe: [mpe2]
      mpi: [spectrum-mpi]
      opencl: [pocl]
      openfoam: [openfoam-com, openfoam-org, foam-extend]
      pil: [py-pillow]
      scalapack: [netlib-scalapack]
      szip: [libszip, libaec]
      tbb: [intel-tbb]
      jpeg: [libjpeg-turbo, libjpeg]
      uuid: [util-linux-uuid, libuuid]
# choices
  hdf5:
    variants: ~mpi
  python:
    variants: ~dbm
  py-numpy:
    variants: ~blas~lapack
# system libs
  perl:
    buildable: false
    externals:
    - prefix: /usr
      spec: perl
  pkg-config:
    buildable: false
    externals:
    - prefix: /usr
      spec: pkg-config
  cuda:
    buildable: false
    externals:
    - prefix: /sw/summit/cuda/11.0.3/
      spec: cuda@11.0.3
  spectrum-mpi:
    buildable: false
    externals:
    - prefix: /sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.1.0/spectrum-mpi-10.4.0.3-20210112-b5zk3valzzwupvryqfd7ouwwir73wats/
      spec: spectrum-mpi@10.4.0%gcc
