compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules:
    # we need this dance to get the compilers to work, it ends up loading
    # gcc/10.3.0
    - PrgEnv-gnu
    - cudatoolkit/21.9_11.4
    - cpe-cuda/21.12
    operating_system: sles15
    paths:
      cc: gcc
      cxx: g++
      f77: gfortran
      fc: gfortran
    spec: gcc@10.3.0
    target: any
