packages:
  all:
    variants: cuda_arch=80 +cuda~openmp~python~shared~mfem
    compiler: [gcc@10.3.0]
    providers:
      mpi: [mpich]
      blas: [openblas]
      lapack: [openblas]
      uuid: [util-linux-uuid, libuuid]
  cray-mpich:
    version: [8.1.12]
    buildable: false
    providers: {}
    compiler: []
    externals:
    - modules:
      - cray-mpich/8.1.12
      spec: cray-mpich@8.1.12
      prefix: /opt/cray/pe/mpich/8.1.12/ofi/gnu/9.1/
  openssl:
    buildable: false
    externals:
    - prefix: /usr
      spec: openssl
  cuda:
    buildable: false
    externals:
    - prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/21.9/cuda/11.4/
      spec: cuda@11.4.0
      modules:
        - cudatoolkit/21.9_11.4
        - cpe-cuda/21.12

